version: '3.7'
services:
  nginx:
    image: nginx:1.14
    networks:
      - net
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./certs/marcoslauder.tech:/certs
    ports:
      - 80:80
networks:
  net:
    driver: bridge

