version: '3.7'
services:
  nginx:
    build: ./
    networks:
      - net
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./certs:/certs
    ports:
      - 80:80
      - 443:443
    working_dir: /usr/share/nginx/html
    command: sass --watch --style=compressed scss:css 
networks:
  net:
    driver: bridge

