version: '3.7'
services:
  nginx:
    image: nginx:1.14
    networks:
      - net
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./certs:/certs
    ports:
      - 80:80
      - 443:443
networks:
  net:
    driver: bridge

